# Generated by Django 3.0.8 on 2020-08-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0003_auto_20200720_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='isRealTime',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='road',
            name='status',
            field=models.CharField(choices=[('1', 'submitted'), ('2', 'approved'), ('3', 'rejected'), ('4', 'workinprogress'), ('5', 'completed')], default='1', max_length=2),
        ),
    ]
