# Generated by Django 3.0.8 on 2020-08-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0004_auto_20200802_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='PCI',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
    ]
